import type { RankingData } from '@/model/ranking/ranking-data.model';

export const dummyRankingData: RankingData = {
  DAY1: {
    TOTAL: [
      {
        id: 'this-is-user-id-11111',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    CAT: [
      {
        id: 'this-is-user-id-11111',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    FOX: [
      {
        id: 'this-is-user-id-11111',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/fox.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/fox.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/fox.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    GOKU: [
      {
        id: 'this-is-user-id-11111',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    REAPER: [
      {
        id: 'this-is-user-id-11111',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    PUDDING: [
      {
        id: 'this-is-user-id-11111',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    TREE: [
      {
        id: 'this-is-user-id-11111',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
  },
  DAY2: {
    TOTAL: [
      {
        id: 'this-is-user-id-11111',
        name: '2日目のユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    CAT: [
      {
        id: 'this-is-user-id-11111',
        name: '2日目のユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    FOX: [
      {
        id: 'this-is-user-id-11111',
        name: '2日目のユーザー名を挿入',
        iconUrl: '/icons/fox.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/fox.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/fox.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    GOKU: [
      {
        id: 'this-is-user-id-11111',
        name: '2日目のユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    REAPER: [
      {
        id: 'this-is-user-id-11111',
        name: '2日目のユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    PUDDING: [
      {
        id: 'this-is-user-id-11111',
        name: '2日目のユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
    TREE: [
      {
        id: 'this-is-user-id-11111',
        name: '2日目のユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 1,
      },
      {
        id: 'this-is-user-id-22222',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 2,
      },
      {
        id: 'this-is-user-id-33333',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 3,
      },
      {
        id: 'this-is-user-id-44444',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 4,
      },
      {
        id: 'this-is-user-id-55555',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 5,
      },
      {
        id: 'this-is-user-id-gfeasg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/tree.png',
        point: 50,
        place: 6,
      },
      {
        id: 'this-is-user-id-gadsrgda',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 7,
      },
      {
        id: 'this-is-user-id-vsdadfg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 8,
      },
      {
        id: 'this-is-user-id-rewefs',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/cat.png',
        point: 50,
        place: 9,
      },
      {
        id: 'this-is-user-id-gfawerg',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/pudding.png',
        point: 50,
        place: 10,
      },
      {
        id: 'this-is-user-id-awertgaf',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/reaper.png',
        point: 50,
        place: 11,
      },
      {
        id: 'this-is-user-id-vasdfge',
        name: 'ここにユーザー名を挿入',
        iconUrl: '/icons/goku.png',
        point: 50,
        place: 12,
      },
    ],
  },
};
