subscription UpdatedRanking($date: RankingPeriod!, $rankingTarget: RankingTarget!){
  updatedRanking(date: $date, rankingTarget: $rankingTarget) {
    point
    user {
      ...UserBioData
    }
  }
}
