subscription UpdatedGameAttenders {
  updatedGameAttenders {
    coinDropping {
      ...GameAttenderBioData
    }
    xeno {
      ...GameAttenderBioData
    }
    iceRaze {
      ...GameAttenderBioData
    }
    poker {
      ...GameAttenderBioData
    }
    president {
      ...GameAttenderBioData
    }
    weDidntPlaytest {
      ...GameAttenderBioData
    }
  }
}
