query FindItemCompletedCharacterStatuses {
  findItemCompletedCharacterStatuses {
    character
    user {
      name
    }
    itemCompletedHistory {
      createdAt
      deliveredAt
      isDelivered
    }
    iconUrl
    id
  }
}
