query FindDetailedGameAttenders {
  getGameAttenders {
    coinDropping {
      ...DetailedGameAttenderData
    }
    xeno {
      ...DetailedGameAttenderData
    }
    iceRaze {
      ...DetailedGameAttenderData
    }
    poker {
      ...DetailedGameAttenderData
    }
    president {
      ...DetailedGameAttenderData
    }
    weDidntPlaytest {
      ...DetailedGameAttenderData
    }
  }
}
