query FindItemCompletedCharacterStatuses {
  findItemCompletedCharacterStatuses {
    character
    user {
      name
      characterStatus {
        id  
      }
    }
    itemCompletedHistory {
      isDelivered
      createdAt
      deliveredAt
    }
    iconUrl
  }
}