name: chromatic

on: push

jobs:
  chromatic-deployment:
    name: Deploy Storybook to chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Storybook with `yarn run sb:build`
        run: yarn run sb:build
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          storybookBuildDir: ./.storybook/static
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
